apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atlantis-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: atlantis
  namespace: atlantis
roleRef:
  kind: ClusterRole
  name: atlantis-cluster-role
  apiGroup: rbac.authorization.k8s.io
